stages:
    - build

before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN hub.036.fr

variables:
    HUB_URL: "hub.036.fr/sushifu/gitlab-dind-runner"
    TAG: ":latest"

build:
    stage: build
    tags:
        - docker
    image: docker:latest
    script:
        - docker info
        - docker build -t $HUB_URL .
        - docker push $HUB_URL$TAG
    only:
        - master
